export const POST_LOGIN_DATA ="POST_LOGIN_DATA";




//Authentication
export const LOGOUT_ACTION ="LOGOUT_ACTION";
export const LOGIN_CONFIRMED_ACTION ="LOGIN_CONFIRMED_ACTION";
export const LOGIN_FAILED_ACTION ="LOGIN_FAILED_ACTION";


//Product Add
export const PRODUCT_ADD_ACTION ="PRODUCT_ADD_ACTION";
export const PRODUCT_LIST_ACTION ="PRODUCT_LIST_ACTION";
export const PRODUCT_SINGLE_ACTION ="PRODUCT_SINGLE_ACTION";
export const PRODUCT_EDIT_ACTION ="PRODUCT_EDIT_ACTION";